### PR TITLE
Minor changes so corrgram accepts any seriation method defined in pac…

### PR DESCRIPTION
**Pull request by mhahsler**
Hi Kevin,

A very small change in corrgram.R lets the function use any of the many ordering methods available in package seriation (if installed).

Best regards,
Michael

### CODE REVIEW

**Review by kwstat — COMMENTED** [review]
Thanks.  Looks pretty good (other than whitespace deletes/adds, oh well).  One question: you added this line:
```
distx <- dist(sqrt(1 - cmat))
```
But when I was looking around for examples, I found this line:
https://search.r-project.org/CRAN/refmans/seriation/html/seriate.html
```
d <- as.dist(sqrt(2 * (1 - corr)))
```
Is the "2" important or is it optional?

**Comment by mhahsler** [comment]
Hmmm, looks like RStudio automatically added the spaces. How annoying! Let me make a new pull request with vim instead so it looks cleaner.

About the distances. The scaling factor does not matter for seriation. I now use the conversion given in:
https://cran.r-project.org/web/packages/smacof/vignettes/smacof.pdf

What I have overlooked is that it needs to be as.dist() instead of dist().

I will send the new pull request sometime later today.

**Comment by mhahsler** [comment]
I have updated the push request to fix the dist calculation. I thought that checking ignore whitespace in RStudio would leave them alone, but it is very adamant about removing them. I hope that is OK with you. You can hide the changed whitespaces on GitHub's 'Files Changed' by clicking on the little gear and checking "Hide whitespaces'.

**Review by kwstat — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
